server:
  port: 9191

spring:
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/order-fallback

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/payment-fallback

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      CircuitBreaker:
        permitted-number-of-calls-in-half-open-state: 3
        event-consumer-buffer-size: 10
        sliding-window-size: 10
        wait-duration-in-open-state: 3s
        sliding-window-type: count-based
        register-health-indicator: true
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5

management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: always